---
abstract: ~
author:
  - '=over 4'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: package-watchdog
no_index:
  directory:
    - inc
    - t
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.01
